#!/usr/bin/perl
use lib "/usr/local/sbin";
use KVM qw(&write_log &success  &fail &attachVolume);

#SYNTAX  qattachvolume <cust_id> <server_id> <volume_name> <storage>
#EXAMPLE qattachvolume mayar testvm01 vda  20

################
##Main
##
#################


my $cust_id=shift;
my $server_id=shift;
my $volume_name=shift;
my $storage=shift;


#####################################################################################################################
if (attachVolume ($cust_id,$server_id,$volume_name,$storage))
 {
        write_log("$volume_name is attached successfully to $cust_id-$server_id \n");
	print success;
        }
else
        {
        write_log("ERROR IN ATTACHING $volume_name \n");
	print fail;
        }
