#!/usr/bin/perl
use lib "/usr/local/sbin";
use KVM qw(&write_log &success  &fail &createBACKUP);

#SYNTAX
#/usr/local/sbin/qcreatebackup '<cust_id>' '<server_id>' '<retention_period>' 'backup_id' 'backup_image_location'
#EXAMPLE
#/usr/local/sbin/qcreatebackup 'mayar' 'vm01' '5' 'bkp001' 'nfs1'


################
##Main
##
#################


my $cust_id=shift;
my $server_id=shift;
my $retention_period=shift;
my $backup_id=shift;
my $image_location=shift;

if (createBACKUP($cust_id,$server_id,$retention_period,$backup_id,$image_location))
 {
	write_log("BACKUP HAS BEEN COMPLETED FOR HOST $server_id, CUSTOMER NAME $cust_id FOR $retention_period DAYS AND BACKUP ID - $backup_id AT LOCATION : $image_location\n");
        print success;
        }
else
        {
	write_log("ERROR IN BACKUP FOR HOST $server_id, CUSTOMER NAME $cust_id FOR $retention_period DAYS AND BACKUP ID - $backup_id AT LOCATION : $image_location \n");
        print fail;
        }
