#!/usr/bin/perl
use lib "/usr/local/sbin";
use KVM qw(&write_log &success  &fail &deallocatePIP);


################
##Main
##
#################

my $cust_id=shift;
my $server_id=shift;
my $cust_name=shift;
my $os_type=shift;
my $os_name=shift;
my $wan_primary_ip=shift;
my $wan_sec_iprem_list=shift;
my $wan_sec_ipleft_list=shift;


if (deallocatePIP($cust_id,$server_id,$cust_name,$os_type,$os_name,$wan_primary_ip,$wan_sec_iprem_list,$wan_sec_ipleft_list))
 {
        write_log("Additional IP's to $cust_id-$server_id of customer $cust_name deallocated");
	#write_log(" Server Details- \n  Customer Name- $cust_name \n Server ID- $server_id \n Root Password- $admin_password \n Primary Ip- $wan_primary_ip \n VNC Port $vm_host_vnc_port \n )";
        print success;
        }
else
        {
        write_log("Error in IP Allocation/DeAllocation.");
        print fail;
        }
