#!/usr/bin/perl
use lib "/usr/local/sbin";
use KVM qw(&write_log &success  &fail &delcustomIMAGE);

#SYNTAX
#/usr/local/sbin/qdelcustomimage '<cust_id>' '<server_id>' '<custom_img_id>' '<custom_img_location>'
#EXAMPLE
#/usr/local/sbin/qdelcustomimage 'mayar' 'vm01' 'vm01-img001' '/customer_custom_images/mayar'

################
##Main
##
#################


my $cust_id=shift;
my $server_id=shift;
my $custom_img_id=shift;
my $custom_img_location=shift;


if (delcustomIMAGE($cust_id,$server_id,$custom_img_id,$custom_img_location))
 {
	write_log("CUSTOM IMAGE $custom_img_id  HAS BEEN DELETED FOR $server_id, CUSTOMER NAME $cust_id AT PATH LOCATION $custom_img_location \n");
        print success;
        }
else
        {
	write_log("ERROR WHILE DELETING CUSTOM IMAGE $custom_img_id FOR $server_id, CUSTOMER NAME \n");
        print fail;
        }
