#!/usr/bin/perl
use lib "/usr/local/sbin";
use KVM qw(&write_log &success  &fail &sshkeydelete);

#SYNTAX
#/usr/local/sbin/qdeletesshkey ‘<cust_id>' '<machine_id>' '<Organization name>'  '<key id>' '<Key name>' '<ssh key values>'
################
##Main
##
#################

my $cust_id=shift;
my $server_id=shift;
my $cust_name=shift;
my $sshkey_id=shift;
my $sshkey_name=shift;
my $sshkey_value=shift;

if (sshkeydelete($cust_id,$server_id,$sshkey_value))
 {
	#write_log("SSH KEY ID: $sshkey_id, KEY NAME: $sshkey_name IS ADDED FOR HOST: $server_id AND CUSTOMER: $cust_id \n");
        print success;
        }
else
        {
	write_log("ERROR SSH KEY ID: $sshkey_id, KEY NAME: $sshkey_name IS ADDED FOR HOST: $server_id AND CUSTOMER: $cust_id \n");
        print fail;
        }
