#!/usr/bin/perl
use lib "/usr/local/sbin";
use KVM qw(&write_log &success  &fail &restoreVIRTUALMACHINE);
#/usr/local/sbin/qrestorevirtualmachine 'cust_id' 'server_id' 'cust_name' 'os_image_location' 'backup_id' 'image_type' 'os_type' 'os_name' 'os_version' 'os_arch' 'hostname' 'ram' 'vcpu' 'storage' 'admin_password' 'wan_mac_address' 'wan_primary_ip' 'wan_sec_ip_list' 'vm_host_vnc_port' 'vnc_password'


################
##Main
##
#################



my $cust_id=shift;
my $server_id=shift;
my $cust_name=shift;
my $os_image_location=shift;
my $backup_id=shift;
my $image_type=shift;
my $os_type=shift;
my $os_name=shift;
my $os_version=shift;
my $os_arch=shift;
my $hostname=shift;
my $ram=shift;
my $vcpu=shift;
my $storage=shift;
my $admin_password=shift;
my $wan_mac_address=shift;
my $wan_primary_ip=shift;
my $wan_sec_ip_list=shift;
my $vm_host_vnc_port=shift;
my $vnc_password=shift; 


write_log("Creation of $cust_id-$server_id server of customer $cust_name is started.");

if (restoreVIRTUALMACHINE($cust_id,$server_id,$cust_name,$os_image_location,$backup_id,$image_type,$os_type,$os_name,$os_version,$os_arch,$hostname,$ram,$vcpu,$storage,$admin_password,$wan_mac_address,$wan_primary_ip,$wan_sec_ip_list,$vm_host_vnc_port,$vnc_password))
 {
        write_log("$cust_id-$server_id of customer $cust_name is successfully created");
        print success;
        }
else
        {
        write_log("Error in Installation::");
        print fail;
        }
